### ISSUE TITLE
Control Sources Packaged into Component-Preload.js

### ISSUE THREAD

**Issue by cschuff** [SAP/ui5-cli#149]
## Expected Behavior
I want to be able to control which files are assembled into Component-preload.js via the projects config (`ui5.yaml`).

## Current Behavior
If found that the task `@ui5/builder.tasks.generateComponentPreload` has a parameter `paths` that can be used for that purpose but I can't find anything on the expected format nor can I manage to force it to do what I want...
I'm trying to achieve something like this (exclude folder `localService` from preload):
```yaml
specVersion: '1.0'
metadata:
  name: test
type: application
componentPreload:
  paths:
    - "**/*.js"
    - "**/!localService/**/*"
```

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by stopcoder** [comment]
Hi @cschuff,

the `@ui5/builder.tasks.generateComponentPreload` creates a bundle for each of the found Component.js file. It includes recursively all files (*.{js,json,xml,html,properties,library}) start from the folder which contains the Component.js file. The customized filtering can't be applied to the bundle generation.

The `paths` parameter controls from which folder the Component.js file(s) can be found.

If you want to generate a custom bundling with self-controlled filters, you can try to use 
`@ui5/builder.tasks.generateBundle` task by writting the following to your ui5.yaml file:

```
builder:
  bundles:
  - bundleDefinition:
      name: component_folder/Component-preload.js
      defaultFileTypes:
      - ".js"
      - ".fragment.xml"
      - ".view.xml"
      - ".properties"
      - ".json"
      sections:
      - mode: preload
        filters:
        - your_filters_here
        resolve: false
    bundleOptions:
      optimize: true
      usePredefineCalls: true
```

The default options for generate Component-preload.js can be found in code https://github.com/SAP/ui5-builder/blob/master/lib/tasks/bundlers/generateComponentPreload.js#L62

I will keep this issue open because we still need to document the options which can be used in bundleDefinition. And you can already try this out.

Best regards,
Jiawei
