### ISSUE TITLE
Allow to serve dist folder, e.g. ui5 serve --dist

### ISSUE THREAD

**Issue by petermuessig** [SAP/ui5-cli#198]
## Expected Behavior
I would like to be able to serve the dist resources via the `ui5 serve` command, e.g. via a dedicated command line options like `--dist`.

## Current Behavior
As of today, the best workaround is to create a separate ui5.yaml file (e.g. ui5-dist.yaml) which shifts the project resources configuration for webapp to the dist folder:

```
specVersion: ‘1.0’
metadata:
 name: openui5-sample-app
type: application
resources:
 configuration:
   paths:
     webapp: dist
```

Now the project can be served from the dist folder via `ui5 serve --config ui5-dist.yaml`.

**Comment by codeworrior** [comment]
This is already on the [roadmap](https://github.com/SAP/ui5-tooling/issues/101) for the ui5 tooling.

**Comment by petermuessig** [comment]
Thanks @codeworrior , I remember again - but I also wanted to document this simple idea here of having just two configuration files and use one for serve from dist.

**Comment by piejanssens** [comment]
It has been on the roadmap for quite some time :-) Any updates in sight?

**Comment by matz3** [comment]
No progress so far and it's also not planned for the next time.

Is there something that you especially expect compared to the workaround mentioned above or using a separate HTTP server like [local-web-server](https://github.com/lwsjs/local-web-server) to serve the dist folder?

**Comment by piejanssens** [comment]
AFAIK it doesn't support relatively loading `src="resources/sap-ui-core.js"` as `ui5 serve` seems to do.

```
specVersion: ‘2.0’
metadata:
 name: openui5-sample-app
type: application
resources:
 configuration:
   paths:
     webapp: dist
```

```
ui5 build
ui5 serve --config ui5-dist.yaml
```

This results in the following error when loading the UI5 app.
`sap-ui-core.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)`
