### ISSUE TITLE
Custom Server Middleware no longer works

### ISSUE THREAD

**Issue by Bomberus** [SAP/ui5-cli#293]
## Expected Behavior
Middleware should be added to server

## Current Behavior
Custom Middleware no longer works with version **1.13.1**.
Same Configuration works in **1.13.0**, no files were changed, just downgraded to this version.

## Steps to reproduce the issue
1. Create custom middleware in ui5.yaml
2. ui5.yaml
```
specVersion: '1.1'
metadata:
  name: nw/core/om/adsconfigui
server:
  customMiddleware:
    - name: cdnProxy
      mountPath: /resources
      beforeMiddleware: serveResources
```

3. add middleware ui5.yaml 
```
---
specVersion: '1.1'
kind: extension
type: server-middleware
metadata:
  name: cdnProxy
middleware:
  path: ./lib/middleware/cdn.js
```

4. middleware js (lib/middleware/cdn.js)
```
if (!!!process.env.CDN_URL){
  require('dotenv').config()
}
var proxy = require('http-proxy-middleware');

module.exports = function({resources, options}) {
  return proxy('**', { target: process.env.CDN_URL, changeOrigin: true, secure: false, auth: ${process.env.auth} } )
};
```

## Context
- Node.js Version: `v12.14.0`
- yarn Version: `1.21.1`
- OS/Platform: `Windows 10 1809`

## Affected components *(if known)*

- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
```
Error Message:
middlewareRepository: Unknown Middleware cdnProxy

Stack Trace:
Error: middlewareRepository: Unknown Middleware cdnProxy
    at Object.getMiddleware (C:\Users\.....\Documents\Projekte\....\node_modules\@ui5\server\lib\middleware\middlewareRepository.js:18:9)
    at MiddlewareManager.addMiddleware (C:\Users\.....\Documents\Projekte\......\node_modules\@ui5\server\lib\middleware\MiddlewareManager.js:37:49)
    at MiddlewareManager.addCustomMiddleware (C:\Users\.....\Documents\Projekte\......\node_modules\@ui5\server\lib\middleware\MiddlewareManager.js:176:15)
    at MiddlewareManager.applyMiddleware (C:\Users\.....\Documents\Projekte\....\....\node_modules\@ui5\server\lib\middleware\MiddlewareManager.js:25:14)
    at async Object.serve (C:\Users\....\Documents\Projekte\.....\node_modules\@ui5\server\lib\server.js:137:3)
    at async Object.serve.handler (C:\Users\.....\Documents\Projekte\....\....\node_modules\@ui5\cli\lib\cli\commands\serve.js:108:33)
